// Generated by gencpp from file differential_drive/SetFloatParam.msg
// DO NOT EDIT!


#ifndef DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAM_H
#define DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAM_H

#include <ros/service_traits.h>


#include <differential_drive/SetFloatParamRequest.h>
#include <differential_drive/SetFloatParamResponse.h>


namespace differential_drive
{

struct SetFloatParam
{

typedef SetFloatParamRequest Request;
typedef SetFloatParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloatParam
} // namespace differential_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::differential_drive::SetFloatParam > {
  static const char* value()
  {
    return "c9ee899b5f0899afa6060c9ba611652c";
  }

  static const char* value(const ::differential_drive::SetFloatParam&) { return value(); }
};

template<>
struct DataType< ::differential_drive::SetFloatParam > {
  static const char* value()
  {
    return "differential_drive/SetFloatParam";
  }

  static const char* value(const ::differential_drive::SetFloatParam&) { return value(); }
};


// service_traits::MD5Sum< ::differential_drive::SetFloatParamRequest> should match
// service_traits::MD5Sum< ::differential_drive::SetFloatParam >
template<>
struct MD5Sum< ::differential_drive::SetFloatParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::differential_drive::SetFloatParam >::value();
  }
  static const char* value(const ::differential_drive::SetFloatParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::differential_drive::SetFloatParamRequest> should match
// service_traits::DataType< ::differential_drive::SetFloatParam >
template<>
struct DataType< ::differential_drive::SetFloatParamRequest>
{
  static const char* value()
  {
    return DataType< ::differential_drive::SetFloatParam >::value();
  }
  static const char* value(const ::differential_drive::SetFloatParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::differential_drive::SetFloatParamResponse> should match
// service_traits::MD5Sum< ::differential_drive::SetFloatParam >
template<>
struct MD5Sum< ::differential_drive::SetFloatParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::differential_drive::SetFloatParam >::value();
  }
  static const char* value(const ::differential_drive::SetFloatParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::differential_drive::SetFloatParamResponse> should match
// service_traits::DataType< ::differential_drive::SetFloatParam >
template<>
struct DataType< ::differential_drive::SetFloatParamResponse>
{
  static const char* value()
  {
    return DataType< ::differential_drive::SetFloatParam >::value();
  }
  static const char* value(const ::differential_drive::SetFloatParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAM_H
