// Generated by gencpp from file differential_drive/SetFloatParamResponse.msg
// DO NOT EDIT!


#ifndef DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAMRESPONSE_H
#define DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace differential_drive
{
template <class ContainerAllocator>
struct SetFloatParamResponse_
{
  typedef SetFloatParamResponse_<ContainerAllocator> Type;

  SetFloatParamResponse_()
    {
    }
  SetFloatParamResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloatParamResponse_

typedef ::differential_drive::SetFloatParamResponse_<std::allocator<void> > SetFloatParamResponse;

typedef boost::shared_ptr< ::differential_drive::SetFloatParamResponse > SetFloatParamResponsePtr;
typedef boost::shared_ptr< ::differential_drive::SetFloatParamResponse const> SetFloatParamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::differential_drive::SetFloatParamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace differential_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::differential_drive::SetFloatParamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "differential_drive/SetFloatParamResponse";
  }

  static const char* value(const ::differential_drive::SetFloatParamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::differential_drive::SetFloatParamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloatParamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::SetFloatParamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::differential_drive::SetFloatParamResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAMRESPONSE_H
