// Generated by gencpp from file differential_drive/SetFloatParamRequest.msg
// DO NOT EDIT!


#ifndef DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAMREQUEST_H
#define DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace differential_drive
{
template <class ContainerAllocator>
struct SetFloatParamRequest_
{
  typedef SetFloatParamRequest_<ContainerAllocator> Type;

  SetFloatParamRequest_()
    : val(0.0)  {
    }
  SetFloatParamRequest_(const ContainerAllocator& _alloc)
    : val(0.0)  {
  (void)_alloc;
    }



   typedef float _val_type;
  _val_type val;





  typedef boost::shared_ptr< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFloatParamRequest_

typedef ::differential_drive::SetFloatParamRequest_<std::allocator<void> > SetFloatParamRequest;

typedef boost::shared_ptr< ::differential_drive::SetFloatParamRequest > SetFloatParamRequestPtr;
typedef boost::shared_ptr< ::differential_drive::SetFloatParamRequest const> SetFloatParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::differential_drive::SetFloatParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::differential_drive::SetFloatParamRequest_<ContainerAllocator1> & lhs, const ::differential_drive::SetFloatParamRequest_<ContainerAllocator2> & rhs)
{
  return lhs.val == rhs.val;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::differential_drive::SetFloatParamRequest_<ContainerAllocator1> & lhs, const ::differential_drive::SetFloatParamRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace differential_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9ee899b5f0899afa6060c9ba611652c";
  }

  static const char* value(const ::differential_drive::SetFloatParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9ee899b5f0899afULL;
  static const uint64_t static_value2 = 0xa6060c9ba611652cULL;
};

template<class ContainerAllocator>
struct DataType< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "differential_drive/SetFloatParamRequest";
  }

  static const char* value(const ::differential_drive::SetFloatParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 val\n"
;
  }

  static const char* value(const ::differential_drive::SetFloatParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFloatParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::differential_drive::SetFloatParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::differential_drive::SetFloatParamRequest_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<float>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFERENTIAL_DRIVE_MESSAGE_SETFLOATPARAMREQUEST_H
